apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
agents: 3
name: test-cluster
volumes:
  - volume: /tmp/k3dvol:/tmp/k3dvol
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
